### ISSUE TITLE
Rename to something else

### ISSUE THREAD

**Issue by YaManicKill** [YaManicKill/blether#1]
As Shuo and Shout are both pretty dying just now, and ignoring my PRs, I want to make this unique.

So, a name. I need a name.

**Comment by YaManicKill** [comment]
Cagair is my current favourite.

**Comment by Cu3PO42** [comment]
Another Scots words (according to some online dictionary): cheep/hark/moot/tittle.

**Comment by YaManicKill** [comment]
Yeah, those are Scots rather than gaidhlig (Cagair is gaidhlig). Interesting ideas. Except, tittle? Really? You know it has a secondary meaning, yes? It's the piece of crap that hangs on the fur of certain animals.

**Comment by Cu3PO42** [comment]
I figured Scots would be what you'd choose. And, no, I didn't know that. Good thing I had the dictionary disclaimer in my comment...

**Comment by NotRaia** [comment]
Are there any Scots words with a similar meaning that start with S?

**Comment by YaManicKill** [comment]
None that I can think of. 

But I think I have a winner. Blether.

It's a word I use all the time and I can't believe it took this long to think about it. I think its also simple to pronounce? Maybe we can test this by asking you guys how you think it is pronounced.

**Comment by Cu3PO42** [comment]
ˈblaθə?

**Comment by NotRaia** [comment]
"Like leather with a B in front"

**Comment by YaManicKill** [comment]
Yes, and that's a genius way of describing it. I will add that to the readme when I change the name. 

Blether it is then.

**Comment by YaManicKill** [comment]
Done
